services:
  backend:
    build:
      context: .
      dockerfile: Containerfile
      secrets:
        - apps_json
    image: hr_photo_checkin:latest
    entrypoint: ["/home/frappe/frappe-bench/entrypoint.sh"]
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      MYSQL_ROOT_PASSWORD: admin
      REDIS_CACHE: redis:6379
      REDIS_QUEUE: redis:6379
      ADMIN_PASSWORD: admin
      # Add these for convenience
      FRAPPE_SITE: frontend
      SITE_NAME: frontend
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
      - ./entrypoint.sh:/home/frappe/frappe-bench/entrypoint.sh:ro
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      restart: unless-stopped

  db:
    image: mariadb:10.6
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--password=admin"]
      interval: 5s
      retries: 20

  redis:
    image: redis:6.2-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

secrets:
  apps_json:
    file: ./apps.json

volumes:
  sites:
  logs:
  db-data:
  redis-data: